name: Deploy Lambda Functions

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}"
          echo "OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}"
          echo "CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}"
          echo "CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}"
          echo "ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}"
          echo "ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}"
          echo "DESO_USER: ${{ secrets.DESO_USER }}"
          echo "DESO_PRIVATE_KEY: ${{ secrets.DESO_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt-get install musl-tools

      - name: Build Lambda Functions
        run: |
          rustup target add x86_64-unknown-linux-musl

          cd backend/lib/lambdas/addPost
          ./build.sh

          cd ../generatePosts
          ./build.sh

          cd ../postToDeso
          ./build.sh

          cd ../postToTwitter
          ./build.sh

          cd ../sendPosts
          ./build.sh

          cd ../getPosts
          ./build.sh

          cd ../addScheduledPost
          ./build.sh

          cd ../editPost
          ./build.sh

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK Stack
        run: |
          cd backend
          npm install
          cdk deploy --require-approval never

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          DESO_USER: ${{ secrets.DESO_USER }}
          DESO_PRIVATE_KEY: ${{ secrets.DESO_PRIVATE_KEY }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
